prepare the changelog for the 6.0.0 release
pulumi/actions pull request #1278
Opened 2024-09-09 11:19 UTC by tgummerer

This includes a breaking change from https://github.com/pulumi/actions/pull/1118, so we should release a new major version.

2024-09-09 14:58 UTC, justinvp requested changes
Before we release this, should we address Komal's comment at https://github.com/pulumi/actions/pull/1118#issuecomment-2021328817?

> Looks like we at least have the refresh option for [up](https://github.com/pulumi/pulumi/commit/f32b16ac0e510b7bbb21bbb41ff906f7f140b9e4) and [preview](https://github.com/pulumi/pulumi/issues/12740) in nodejs automation api, but would be great to get this supported for `destroy` as well to have consistency across commands.

Otherwise, it looks like if you're running `destroy` with the `refresh` option set, we no longer do a refresh at all.

2024-09-09 16:18 UTC, tgummerer commented
https://github.com/pulumi/pulumi/pull/17209 has the changes.  We can merge this after merging and releasing that.

2024-09-25 13:33 UTC, tgummerer commented
Indeed, thank you! I submitted a PR to update the pulumi version in this repo here: https://github.com/pulumi/actions/pull/1287

Once that's merged I think we can go ahead with the release!

2024-09-26 13:58 UTC, julienp approved these changes

2024-09-26 14:02 UTC, fitz-vivodyne commented on CHANGELOG.md
>  - feat: (breaking change) Update the `refresh` option to runcommands with the
```suggestion
- feat: (breaking change) Update the `refresh` option to run commands with the
```

2024-09-26 14:23 UTC, tgummerer commented on CHANGELOG.md
>  - feat: (breaking change) Update the `refresh` option to runcommands with the
Thanks!

2024-09-26 17:58 UTC, justinvp approved these changes
LGTM otherwise

2024-09-26 17:58 UTC, justinvp commented on CHANGELOG.md
> +## 6.0.0 (2024-09-09)
Needs updated date.

2024-09-27 08:30 UTC, tgummerer commented on CHANGELOG.md
> +## 6.0.0 (2024-09-09)
Done, thanks!

2024-09-27 08:34 UTC, merged