docs: Add example for Google Workflow Identity Federation
pulumi/actions pull request #747
Opened 2022-10-06 20:19 UTC by cobraz

2022-10-07 12:58 UTC, cobraz commented on examples/nodejs-google-workload-identity-federation.yaml
> +          cloud-url: gs://my-bucket-name
Sure, but I feel that falls outside of this example, right? Users might even use Google KMS, which would move this configuration outside of this example.

2022-10-07 13:09 UTC, Frassle commented on examples/nodejs-google-workload-identity-federation.yaml
> +          cloud-url: gs://my-bucket-name
If they we're they'd still need to set secrets-provider in the action config. There's no environment in which this example would work, and that feels like a bad example.

2022-10-07 13:14 UTC, cobraz commented on examples/nodejs-google-workload-identity-federation.yaml
> +          cloud-url: gs://my-bucket-name
Isn't that normal?

2022-10-07 13:23 UTC, Frassle commented on examples/nodejs-google-workload-identity-federation.yaml
> +          cloud-url: gs://my-bucket-name
Eh although seems we don't do this for _any_ other examples so 🤷‍♂️ maybe its not imporant.

2022-10-07 14:20 UTC, cobraz commented on examples/nodejs-google-workload-identity-federation.yaml
> +          cloud-url: gs://my-bucket-name
I can only speak for what I've seen out in the wild, which is that most use Google KMS.

Maybe we can cover both areas with a simple comment?

```suggestion
          cloud-url: gs://my-bucket-name
        # If you're not using Google KMS, you probably need to PULUMI_CONFIG_PASSPHRASE
        # 
        # example:
        # env:
        #  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

Something like that?

2022-10-07 17:42 UTC, RobbieMcKinstry commented on examples/nodejs-google-workload-identity-federation.yaml
> +      - name: Checkout 🛎️
Love the emojis!

2022-10-07 17:56 UTC, RobbieMcKinstry commented on examples/nodejs-google-workload-identity-federation.yaml
> +          cloud-url: gs://my-bucket-name
I don't have a ton of context on this backend, so forgive me if my response isn't apropos.

1. I think our examples should aim to be _complete_ and _minimal_. That is, they should contain all of the necessary configuration, and should only include code necessary to convey the minimal example. In this case, I think that means assuming Google Blob Storage is used for state management while the Pulumi Service is used for secret management. Assuming they use Google KMS for secret management violates the goal of minimalism, and eliding the `PULUMI_ACCESS_TOKEN` would violate _completion_.

2. As such, I'd suggest the inverse of @cobraz's suggestion above:

```yaml
# You can elide PULUMI_ACCESS_TOKEN below if you're using Google KMS for secret encryption.
env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```
 I'd include the access token, and add a comment saying you can remove it if you set up Google KMS.

2022-10-07 17:58 UTC, RobbieMcKinstry requested changes
I left a comment weighing in on the discussion above. Otherwise, the example looks good to me! :D  

Feel free to re-request review whenever you want :)

2022-10-07 20:14 UTC, Frassle commented on examples/nodejs-google-workload-identity-federation.yaml
> +          cloud-url: gs://my-bucket-name
> I think that means assuming Google Blob Storage is used for state management while the Pulumi Service is used for secret management

Just an FYI that that is not supported. Service secrets are tied to stacks.

2022-10-18 18:25 UTC, cobraz commented on examples/nodejs-google-workload-identity-federation.yaml
> +          cloud-url: gs://my-bucket-name
How about this?

[`9b4b5aa` (#747)](https://github.com/pulumi/actions/pull/747/commits/9b4b5aafb2c567fa7b7fdf86ed08a831e5e3872b)

2022-11-14 23:21 UTC, RobbieMcKinstry approved these changes

2022-11-14 23:22 UTC, RobbieMcKinstry commented
Looks like @Frassle concern has been resolved; I'm going to merge. We can always back it out of follow-on if there's an issue.

2022-11-14 23:22 UTC, merged